version: '3.1'

services:
  db:
    image: postgres
    restart: always
    container_name: portfolio-db
    environment:
      POSTGRES_DB: portfolio
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
    ports:
      - "5433:5432"